from collections import defaultdict

from devdna.schemas import EvidenceSource, ReadmeDraft, ReadmeRepository, ReportSnapshot

README_SCHEMA_VERSION = "1"
README_GENERATOR_VERSION = "evidence-readme-v1"


def repository_url(repository: str) -> str:
    return f"https://github.com/{repository}"


def unique_evidence_sources(report: ReportSnapshot) -> list[EvidenceSource]:
    sources: dict[tuple[str, str], EvidenceSource] = {}
    for strength in report.strengths:
        for source in strength.sources:
            sources[(source.repository, source.path)] = source
    return [sources[key] for key in sorted(sources)]


def generate_profile_readme(username: str, report: ReportSnapshot) -> ReadmeDraft:
    evidence_by_repository: dict[str, set[str]] = defaultdict(set)
    for strength in report.strengths:
        for repository_name in strength.repositories:
            evidence_by_repository[repository_name].add(strength.title)

    repositories = [
        ReadmeRepository(
            name=repository_name,
            url=repository_url(repository_name),
            evidence=sorted(titles),
        )
        for repository_name, titles in sorted(evidence_by_repository.items())
    ]
    sources = unique_evidence_sources(report)

    profile_summary = (
        "Python backend developer with public project evidence across "
        + ", ".join(strength.title.lower() for strength in report.strengths[:3])
        + "."
        if report.strengths
        else "Building toward Python backend development through public, reviewable projects."
    )
    lines = [
        f"# {username}",
        "",
        profile_summary,
        "",
    ]
    if repositories:
        lines.extend(["## Selected projects", ""])
        for draft_repository in repositories[:4]:
            evidence = ", ".join(draft_repository.evidence)
            lines.append(f"- [{draft_repository.name}]({draft_repository.url}) - {evidence}")
        lines.append("")

    if report.strengths:
        lines.extend(["## Engineering evidence", ""])
        for strength in report.strengths:
            source = strength.sources[0]
            lines.append(f"- [{strength.title}]({source.url}) - {strength.summary}")
        lines.append("")

    if report.actions:
        lines.extend(["## Currently strengthening", ""])
        for action in report.actions[:3]:
            lines.append(f"- {action.title}: {action.rationale}")
        lines.append("")

    lines.extend(
        [
            "## Connect",
            "",
            f"- GitHub: https://github.com/{username}",
            "",
            (
                "<!-- Generated by DevDNA from public repository evidence. "
                "Review before publishing. -->"
            ),
        ]
    )
    return ReadmeDraft(
        schema_version=README_SCHEMA_VERSION,
        generator_version=README_GENERATOR_VERSION,
        github_username=username,
        repositories=repositories,
        evidence_sources=sources,
        markdown="\n".join(lines),
    )
