from collections import defaultdict

from devdna.schemas import EvidenceSource, ReadmeDraft, ReadmeRepository, ReportSnapshot

README_SCHEMA_VERSION = "1"
README_GENERATOR_VERSION = "evidence-readme-v2"
README_STYLES = ("minimal", "badges", "centered")


def repository_url(repository: str) -> str:
    return f"https://github.com/{repository}"


def badge(label: str, message: str, color: str = "2b7489") -> str:
    return f"https://img.shields.io/badge/{label}-{message}-{color}"


def unique_evidence_sources(report: ReportSnapshot) -> list[EvidenceSource]:
    sources: dict[tuple[str, str], EvidenceSource] = {}
    for strength in report.strengths:
        for source in strength.sources:
            sources[(source.repository, source.path)] = source
    return [sources[key] for key in sorted(sources)]


def technology_badges(report: ReportSnapshot, max_badges: int = 8) -> list[str]:
    return [
        badge("tech", technology, "informational") for technology in report.tech_stack[:max_badges]
    ]


def metrics_badges(username: str) -> list[str]:
    return [
        badge("", "open source", "brightgreen"),
        badge("focus", "production quality", "blueviolet"),
        badge("status", "improving", "yellow"),
        f"https://img.shields.io/badge/GitHub-@{username}-181717?logo=github",
    ]


def render_badge_line(badges: list[str]) -> str:
    return " ".join(f"![badge]({url})" for url in badges)


def render_header(username: str, report: ReportSnapshot, style: str) -> list[str]:
    profile_summary = (
        "Python backend developer with public project evidence across "
        + ", ".join(strength.title.lower() for strength in report.strengths[:3])
        + "."
        if report.strengths
        else "Building toward Python backend development through public, reviewable projects."
    )
    title = f"# {username}"
    if style == "centered":
        lines = [
            f'<div align="center">\n\n## {username}',
            "",
            profile_summary,
            "",
            render_badge_line(metrics_badges(username)),
            "",
            render_badge_line(technology_badges(report)),
            "",
        ]
        if report.tech_stack:
            lines.extend(
                [
                    f"![GitHub stats](https://github-readme-stats.vercel.app/api?username={username}&show_icons=true&hide_border=true)",
                    "",
                ]
            )
        lines.extend(
            [
                f"![Top languages](https://github-readme-stats.vercel.app/api/top-langs/?username={username}&layout=compact&hide_border=true)",
                "",
                "</div>",
                "",
            ]
        )
        return lines
    lines = [title, "", profile_summary, ""]
    if style == "badges":
        lines.extend([render_badge_line(metrics_badges(username)), ""])
        if report.tech_stack:
            lines.extend([render_badge_line(technology_badges(report)), ""])
    return lines


def generate_profile_readme(
    username: str,
    report: ReportSnapshot,
    style: str = "minimal",
) -> ReadmeDraft:
    evidence_by_repository: dict[str, set[str]] = defaultdict(set)
    for strength in report.strengths:
        for repository_name in strength.repositories:
            evidence_by_repository[repository_name].add(strength.title)

    repositories = [
        ReadmeRepository(
            name=repository_name,
            url=repository_url(repository_name),
            evidence=sorted(titles),
        )
        for repository_name, titles in sorted(evidence_by_repository.items())
    ]
    sources = unique_evidence_sources(report)

    lines = render_header(username, report, style)
    if repositories:
        lines.extend(["## Selected projects", ""])
        for draft_repository in repositories[:4]:
            evidence = ", ".join(draft_repository.evidence)
            lines.append(f"- [{draft_repository.name}]({draft_repository.url}) - {evidence}")
        lines.append("")

    if report.strengths:
        lines.extend(["## Engineering evidence", ""])
        for strength in report.strengths:
            source = strength.sources[0]
            lines.append(f"- [{strength.title}]({source.url}) - {strength.summary}")
        lines.append("")

    if report.actions:
        lines.extend(["## Currently strengthening", ""])
        for action in report.actions[:3]:
            lines.append(f"- {action.title}: {action.rationale}")
        lines.append("")

    lines.extend(
        [
            "## Connect",
            "",
            f"- GitHub: https://github.com/{username}",
            "",
            (
                "<!-- Generated by DevDNA from public repository evidence. "
                "Review before publishing. -->"
            ),
        ]
    )
    return ReadmeDraft(
        schema_version=README_SCHEMA_VERSION,
        generator_version=README_GENERATOR_VERSION,
        github_username=username,
        repositories=repositories,
        evidence_sources=sources,
        style=style,
        markdown="\n".join(lines),
    )
